# Generated by Django 4.1.7 on 2023-03-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes_app', '0002_author_quote_delete_storypost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
    ]
